FROM ubuntu:20.04

LABEL maintainer="fakebilly.work@outlook.com"
LABEL org.opencontainers.image.authors="FakeBilly"

ARG DEBIAN_FRONTEND=noninteractive
ARG USER_NM=root
ARG USER_PWD=dev1024

RUN apt update \
    && apt install --no-install-recommends -y sudo dialog apt-utils \
    && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
    && apt install --no-install-recommends -y apt-transport-https ca-certificates \
    && apt install --no-install-recommends -y  locales \
    && sed -ie 's/# zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/g' /etc/locale.gen \
    && sed -ie 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen \
    && echo "$USER_NM:$USER_PWD" | chpasswd

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8 \
    LC_NUMERIC=en_US.UTF-8 \
    LC_TIME=en_US.UTF-8 \
    LC_COLLATE=en_US.UTF-8 \
    LC_MONETARY=en_US.UTF-8 \
    LC_MESSAGES=en_US.UTF-8 \
    LC_PAPER=en_US.UTF-8 \
    LC_NAME=en_US.UTF-8 \
    LC_ADDRESS=en_US.UTF-8 \
    LC_TELEPHONE=en_US.UTF-8 \
    LC_MEASUREMENT=en_US.UTF-8 \
    LC_IDENTIFICATION=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

WORKDIR /$USER_NM

USER $USER_NM